var nodes = [
  {id: 1, label: 'Trump', title: 'City: ' + 'Chicago', value: 30, group: 1},
  {id: 2, label: 'Trump', title: 'City: ' + 'NewYork', value:40, group: 2 },
  {id: 3, label: 'Trump', title: 'City: ' + 'Los Angels', value: 10, group: 3},
  {id: 4, label: 'Trump', title: 'City: ' + 'Atlanta', value: 20, group: 4},
  {id: 5, label: 'Trump', title: 'City: ' + 'Washington DC', value: 5, group: 5},
  {id: 6, label: 'Trump', title: 'City: ' + 'Seattle', value: 10, group: 6},
  {id: 7, label: 'Trump', title: 'City: ' + 'San Francisco', value: 20, group: 7},
  {id: 8, label: 'Obama', title: 'City: ' + 'Chicago', value: 10, group: 1},
  {id: 9, label: 'Obama', title: 'City: ' + 'NewYork', value: 20, group: 2},
  {id: 10, label: 'Obama', title: 'City: ' + 'Los Angels', value: 30, group: 3},
  {id: 11, label: 'Obama', title: 'City: ' + 'Atlanta', value: 20, group: 4},
  {id: 12, label: 'Movie', title: 'City: ' + 'Washington DC', value: 10, group: 5},
  {id: 13, label: 'Movie', title: 'City: ' + 'NewYork', value: 30, group: 2},
  {id: 14, label: 'Movie', title: 'City: ' + 'Atlanta', value: 20, group: 4},
  {id: 15, label: 'Movie', title: 'City: ' + 'Seattle', value: 10, group: 6},
  {id: 16, label: 'Healthcare', title: 'City: ' + 'Washington DC', value: 20, group: 5},
  {id: 17, label: 'Healthcare', title: 'City: ' + 'NewYork', value: 10, group: 2},
  {id: 18, label: 'Healthcare', title: 'City: ' + 'Chicggo', value: 30, group: 1},
  {id: 19, label: 'Healthcare', title: 'City: ' + 'Los Angels', value: 10, group: 3},
 

];
// create an array with edges
var edges = [
  {from: 1, to: 2},
  {from: 1, to: 3},
  {from: 1, to: 4},
  {from: 1, to: 5},
  {from: 1, to: 6},
  {from: 1, to: 7},
  {from: 2, to: 3},
  {from: 2, to: 4},
  {from: 2, to: 5},
  {from: 2, to: 6},
  {from: 2, to: 7},
  {from: 3, to: 4},
  {from: 3, to: 5},
  {from: 3, to: 6},
  {from: 3, to: 7},
  {from: 4, to: 5},
  {from: 4, to: 6},
  {from: 4, to: 7},
  {from: 5, to: 6},
  {from: 5, to: 7},
  {from: 6, to: 7},
  {from: 8, to: 9},
  {from: 8, to: 10},
  {from: 8, to: 11},
  {from: 9, to: 10},
  {from: 9, to: 11},
  {from: 10, to: 11},
  {from: 5, to: 1},
  {from: 6, to: 8},
  {from: 7, to: 9},
  {from: 8, to: 3},
  {from: 9, to: 4},
  {from: 10, to: 6},
  {from: 11, to: 9},
  {from: 12, to: 10},
  {from: 13, to: 9},
  {from: 14, to: 13},
  {from: 15, to: 17},
  {from: 16, to: 18},
  {from: 17, to: 6},
];
